Add auth setup for private registry with scope
oven-sh/setup-bun pull request #16
Opened 2023-09-09 03:11 UTC by vitoorgomes

Bun is awesome, but I've seen too many workarounds to make authentication for a private package under a registry-url (like `'https://npm.pkg.github.com/'`) with a scope

Heavily inspired by the `setup-node` action, I created this to support this feature

I've tested a lot on a private personal org with a private package and my repo that installs the private package on CI worked like a charm.

<img width="546" alt="image" src="https://github.com/oven-sh/setup-bun/assets/41302394/6507cba4-e8d5-4494-a25f-b9c1cfbac815">

![SCR-20230909-6r](https://github.com/oven-sh/setup-bun/assets/41302394/3f0d4110-858c-413f-8e9b-32f390035705)

Also `"@actions/cache"` import was duplicated on `setup.ts` and now I left only `import * as cache from "@actions/cache";`

2023-09-09 06:29 UTC, zerocowl reviewed
@vitoorgomes Nice job! I also have some suggestions

2023-09-09 06:29 UTC, zerocowl commented on src/auth.ts
> +
Considering good security practices and CI processes, I suggest changing the setting to token structure and not username/password:
```suggestion
const bunRegistryString = `'${scope}' = { token = "$BUN_AUTH_TOKEN", url = "${registryUrl}"}`;

```

2023-09-09 06:29 UTC, zerocowl commented on dist/auth.js
> +    newContents += `[install.scopes]${EOL}${EOL}${bunRegistryString}${EOL}`;
add a fallback if the 'scope' is not configured to use only ``` [install] ```

2023-09-23 08:36 UTC, CyberFlameGO requested changes
Might wanna remove `node_modules` - generally this shouldn't be committed

2023-09-26 15:13 UTC, xHyroM commented
There are some conflicts, can you resolve them?

2023-10-17 18:48 UTC, vitoorgomes commented
> Might wanna remove `node_modules` - generally this shouldn't be committed

when I forked `node_modules` were still a thing in this repo, gladly it was removed I also removed from this PR

2023-10-17 18:49 UTC, vitoorgomes commented
> There are some conflicts, can you resolve them?

didn't had free time sooner, but it's done

2023-10-25 13:14 UTC, xHyroM commented
can you rebuild it one more time please?

2023-10-25 20:21 UTC, vitoorgomes commented
> can you rebuild it one more time, please? Then ping me, i'll merge.

sure, done

2023-11-01 09:14 UTC, xhyrom approved these changes

2023-11-01 09:17 UTC, merged