Add no-cache option
oven-sh/setup-bun pull request #58
Opened 2024-02-09 15:54 UTC by maschwenk

2024-02-16 22:15 UTC, Electroid commented on action.yml
> +  disable-cache:
I think it makes sense to call this `no-cache`

2024-02-22 18:00 UTC, maschwenk commented
@Electroid addressed those changes, also integrated some of the changes from:

- https://github.com/oven-sh/setup-bun/pull/62

by @Akalanka47000

2024-02-22 18:01 UTC, maschwenk commented on package.json
> +  "version": "1.2.0",
Unsure if this is better left to you guys

2024-02-22 20:41 UTC, Electroid approved these changes
Thanks for working on this, looks good!

2024-02-22 20:44 UTC, Jarred-Sumner requested changes
CI failing

2024-02-22 20:59 UTC, maschwenk commented
I think I fixed it, but let me also take a look at running these same CI tests on my branch or by just triggering from another repo. Apologies.

2024-02-23 16:10 UTC, maschwenk commented
@Electroid @Jarred-Sumner I think we're good now!

2024-02-23 19:09 UTC, Electroid approved these changes
CI now passes, thanks!

2024-02-23 19:09 UTC, merged