feat: add input for bun-version-file
oven-sh/setup-bun pull request #76
Opened 2024-04-04 10:21 UTC by adeherysh

## What does this PR do?
- feat: add input for bun-version-file

2024-04-04 14:33 UTC, xHyroM requested changes

2024-04-04 14:33 UTC, xHyroM commented on README.md
> +| `bun-version-file`  | The version of Bun to download and install from file.  | `undefined` | `canary`, `1.0.0`, `1.0.x`      |
You have bad examples here.

2024-04-04 14:36 UTC, xHyroM commented
In the main file there's a lot of boilerplate code - we could reduce it. Can you do it? If not, i can do it as well. Also this is a breaking change, we would have to release `2.0.0`.

2024-04-09 16:45 UTC, adeherysh commented
> I'm not a big fan of `x-file` - it looks horrible. What about allowing files directly in `bun-version` instead of having two properties for the same thing? Also this is a breaking change thus it would appear in `2.0.0`.

Imo this config usefull for monorepo when using single workflow, just create .bumrc file inside each package, and this config can make consistency bun installed version between when running in local or ci

2024-04-09 17:11 UTC, adeherysh commented on README.md
> +| `bun-version-file`  | The version of Bun to download and install from file.  | `undefined` | `canary`, `1.0.0`, `1.0.x`      |
Thanks, lemme check

2024-04-12 06:55 UTC, xHyroM approved these changes
LGTM; I'll create branch called `dev` because I want to do some more changes

2024-04-12 20:17 UTC, merged

2024-05-06 02:52 UTC, adeherysh commented
> LGTM; I'll create branch called `dev` because I want to do some more changes

oke thanks @xHyroM

2024-06-24 10:31 UTC, michaelmior commented
Is this supposed to be called `.bumrc` by default and not `.bunrc`?

2024-06-24 10:37 UTC, Jarred-Sumner commented
> Is this supposed to be called `.bumrc` by default and not `.bunrc`?

It is not supposed to be called `.bumrc` or `.bunrc`

2024-06-24 10:40 UTC, michaelmior commented
@Jarred-Sumner The example given is `.bumrc`, so I'm confused by your comment. I was just wondering if there was a typo that should be corrected.

2024-06-24 10:57 UTC, Jarred-Sumner commented
Yep, thanks for flagging

2024-06-24 13:15 UTC, xHyroM commented
> @Jarred-Sumner The example given is `.bumrc`, so I'm confused by your comment. I was just wondering if there was a typo that should be corrected.

Fixed in https://github.com/oven-sh/setup-bun/pull/86, thanks for flagging :)